name: "Splight Push Component"
description: "Automatically find updated components and push them to Splight Hub."
author: "Marco Martinelli"
inputs:
  splight_access_id: # TODO: a true
    description: "Splight Hub access key id."
    required: false
  splight_secret_key:
    description: "Splight Hub private key."
    required: false
  splight_platform_api_host:
    description: "Splight platform API endpoint."
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.splight_access_id }}
    - ${{ inputs.splight_secret_key }}
    - ${{ inputs.splight_platform_api_host }}
    - ${{ inputs.spec_file }}